# -*- coding: utf-8 -*-
"""jarvis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15kx5UsJqk9nNIAsAfyOBU2r63ADYzOpd
"""

import pyttsx3
import datetime
import speech_recognition as sr



engine = pyttsx3.init('sapi5')
voices = engine.getProperty("voices")
# print(voices)
engine.setProperty('voice', voices[0].id)
# print(voices[0].id)



def speak(audio):
    engine.say(audio)
    engine.runAndWait()


def wishMe():
    hour = int(datetime.datetime.now().hour)
    if hour >= 0 and hour < 12:
        speak("Good Morning Himanshu, Have a productive day ahead.")
    elif hour >= 12 and hour < 18:
        speak("Good afternoon")
    else:
        speak("Good Evening")

    speak("I am Jarvis sir. Please tell me how may I help you.")

def takeCommand():
    # It takes microphone input from the user and returns string output.
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening....")
        r.pause_threshold = 1  # seconds of non-speaking audio before a phrase is considered complete
        audio = r.listen(source)

    try:
        print("Recognizing...")
        query = r.recognize_google(audio, language = 'en-in')
        print("User said:", query)

    except Exception as e:
        print(e)

        print("Say that again please....")
        return "None"
    return query


if __name__ == "__main__":
    wishMe()
    takeCommand()